name: CI

on:
  pull_request:

jobs:
  ci:
    name: Building ${{ matrix.file }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        file:
          - sonoff-m5-1c.yaml
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Build ESPHome firmware to verify configuration
        uses: esphome/build-action@v2
        with:
          yaml_file: ${{ matrix.file }}
